<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">
    <!-- *origin refers to the first element in <xacro:arm> -->
    <xacro:macro name="arm" params="parent prefix *origin">
        <!-- Constants for robot dimensions -->
        <xacro:property name="mass" value="1" /> <!-- arbitrary value for mass -->
        <xacro:property name="width" value="0.1" /> <!-- Square dimensions (widthxwidth) of beams -->
        <xacro:property name="height1" value="2" /> <!-- Link 1 -->
        <xacro:property name="height2" value="1" /> <!-- Link 2 -->
        <xacro:property name="offset" value="0.05" /> 

        <joint name="${prefix}base" type="fixed">
            <xacro:insert_block name="origin" />
            <parent link="${parent}" />
            <child link="${prefix}arm1"/>
        </joint>

        <link name="${prefix}arm1">
            <collision>
                <origin xyz="0 0 ${height1 / 2}" rpy="0 0 0"/>
                <geometry>
                    <box size="${width} ${width} ${height1}"/>  
                </geometry>
            </collision>
            
            <visual>
                <origin xyz="0 0 ${height1 / 2}" rpy="0 0 0"/>
                <geometry>
                    <box size="${width} ${width} ${height1}"/>    
                </geometry>
            </visual>

            <interial>
                <origin xyz="0 0 ${height1 / 2}"/>
                <mass value="${mass}" />
                <inertia ixx="${mass / 12 * (width*width + height1*height1)}" ixy="0.0" ixz="0.0" iyy="{mass / 12 * (width*width + height1*height1)}" iyz="0.0" izz="{mass / 12 * 2*width*width}"/>
            </interial>
        </link>

        <joint name="${prefix}joint1" type="revolute">
            <parent link="${prefix}arm1"/>
            <child link="${prefix}arm2"/>
            <origin xyz="0 ${width} ${height1 / 2 - offset}"/>
            <axis xyz="0.0 1.0 0.0"/>
            <dynamics damping="0.7"/>
        </joint>

        <link name="${prefix}arm2">
            <collision>
                <origin xyz="0 ${width} ${height2 / 2 - offset}" rpy="0 0 0"/>
                <geometry>
                    <box size="${width} ${width} ${height2}"/>  
                </geometry>
            </collision>
            
            <visual>
                <origin xyz="0 ${width} ${height2 / 2 -offset}" rpy="0 0 0"/>
                <geometry>
                    <box size="${width} ${width} ${height2}"/>    
                </geometry>
            </visual>

            <interial>
                <origin xyz="0 0 ${height2}"/>
                <mass value="${mass}" />
                <inertia ixx="${mass / 12 * (width*width + height2*height2)}" ixy="0.0" ixz="0.0" iyy="{mass / 12 * (width*width + height2*height2)}" iyz="0.0" izz="{mass / 12 * 2*width*width}"/>
            </interial>
        </link>
    </xacro:macro>
</robot>